occlient:
  image: toughiq/owncloud-client
  volumes:
    - ${PWD}/mydata:/ocdata
  environment:
    - OC_USER=yansinan@163.com
    - OC_PASS=ccf5f287
    - OC_PROTO=https
    - OC_SERVER=myocserver.com
    - OC_URLPATH=/
    - OC_WEBDAV=remote.php/webdav
    - OC_FILEPATH=/
    - TRUST_SELFSIGN=0
    - SYNC_HIDDEN=0
    - SILENCE_OUTPUT=1
    - RUN_INTERVAL=30
    - RUN_UID=1000

